name: Ruby
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
      
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:  
      - name: Setup ubuntu
        run: |
          sudo apt-get install build-essential libcurl4-openssl-dev
          sudo apt-get install libz-dev libiconv-hook1 libiconv-hook-dev
          sudo apt-get update
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
          sudo service mysql start
          sudo mysql --host localhost --port ${{ job.services.mysql.ports[3306] }} -uroot -puser -e "SHOW GRANTS FOR 'root'@'localhost'"
      
      - name: Bundle Install and Create DB
        env:
          RAILS_ENV: test
          DB_PASSWORD: user 
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          gem install bundler --version 2.1.4
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare --trace
          
      - name: Run tests
        env:
          DB_PASSWORD: user
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          RAILS_ENV: test
        run: bundle exec rspec
